"""create database

Revision ID: 0c1c55f060f5
Revises: 
Create Date: 2023-06-02 05:36:25.668729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c1c55f060f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('talks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talk_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('talk_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['talk_id'], ['talks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('talk_elements')
    op.drop_table('talks')
    # ### end Alembic commands ###
